# Generated by Django 3.1 on 2020-08-28 19:21

from django.db import migrations


roles = [
    'Tank',
    'Healer',
    'Ranged',
    'Melee',
]


classes = [
    'death_knight',
    'demon_hunter',
    'druid',
    'hunter',
    'mage',
    'monk',
    'paladin',
    'priest',
    'rogue',
    'shaman',
    'warlock',
    'warrior',
]


# forward function
def add_data(apps, schema_editor):
    role_model = apps.get_model('raid_roster_drf', 'Role')
    game_class_model = apps.get_model('raid_roster_drf', 'GameClass')

    for rl in roles:
        role_model.objects.get_or_create(name=rl)

    for cl in classes:
        game_class_model.objects.get_or_create(name=cl)


# forward function
def remove_data(apps, schema_editor):
    role_model = apps.get_model('raid_roster_drf', 'Role')
    game_class_model = apps.get_model('raid_roster_drf', 'GameClass')

    role_model.objects.filter(name__in=roles).delete()
    game_class_model.objects.filter(name__in=classes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('raid_roster_drf', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            add_data,
            remove_data
        )
    ]
