# Generated by Django 3.1 on 2020-08-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raid_roster_drf', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_main',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
