# Generated by Django 3.1 on 2020-09-18 20:43

from django.db import migrations, models
import django.db.models.deletion


def shuffle_that_stupid_data_around(apps, schema_editor):
    role_model = apps.get_model('raid_roster_drf', 'Role')
    character_model = apps.get_model('raid_roster_drf', 'Character')

    for character in character_model.objects.all():
        character.main_role = character.role.all()[0]
        character.off_spec_roles.add(*character.role.all()[1:])
        character.save()


def there_is_nothing_done_on_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('raid_roster_drf', '0003_character_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='off_spec_roles',
            field=models.ManyToManyField(related_name='off_spec', to='raid_roster_drf.Role'),
        ),
        migrations.AddField(
            model_name='character',
            name='main_role',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='main_spec', to='raid_roster_drf.role'),
            preserve_default=False,
        ),
        migrations.RunPython(
            shuffle_that_stupid_data_around,
            there_is_nothing_done_on_reverse
        )
    ]
