# Generated by Django 3.1 on 2020-09-18 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raid_roster_drf', '0004_add_off_spec_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='role',
        ),
        migrations.AlterField(
            model_name='character',
            name='main_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_spec_characters', to='raid_roster_drf.role'),
        ),
        migrations.AlterField(
            model_name='character',
            name='off_spec_roles',
            field=models.ManyToManyField(related_name='off_spec_characters', to='raid_roster_drf.Role'),
        ),
    ]
